In [1]:
from IPython.display import clear_output # clear_output() 으로 아웃풋 제거 가능
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import numpy as np
import scipy as sp
import pandas as pd
import statsmodels.api as sm
import statsmodels.formula.api as smf
import statsmodels.stats.api as sms
import sklearn as sk

%matplotlib inline
%config InlineBackend.figure_formats = {'png','retina'}

import matplotlib as mpl
import matplotlib.pylab as plt
from mpl_toolkits.mplot3d import Axes3D

import seaborn as sns
sns.set()
sns.set_style("whitegrid")
sns.set_color_codes()

pd.set_option('display.max_columns', 200)
pd.set_option('display.width', 1000)

#한글폰트 적용
from matplotlib import font_manager, rc
font_name = font_manager.FontProperties(fname="c:/Windows/Fonts/malgun.ttf").get_name()
rc('font', family=font_name)
#음수처리
mpl.rcParams['axes.unicode_minus'] = False

# ■ Konlpy의 Okt(twitter)로 토크나이징하기 (연습)

In [3]:
# Konlpy의 Okt(twitter)로 토크나이징하기
from konlpy.corpus import kolaw
from konlpy.tag import *
import konlpy

In [4]:
kolaw.fileids()
c = kolaw.open('constitution.txt').read()
print(c[:100])

['constitution.txt']

대한민국헌법

유구한 역사와 전통에 빛나는 우리 대한국민은 3·1운동으로 건립된 대한민국임시정부의 법통과 불의에 항거한 4·19민주이념을 계승하고, 조국의 민주개혁과 평화적 통일의

In [14]:
kkma = Kkma()
komoran = Komoran()
hanna = Hannanum()

openkoreantext = Okt()

In [80]:
ex_text = "아이폰 기다리다 지쳐 애플공홈에서 언락폰질러버렸다 6+ 128기가실버ㅋ"
# Mecab.nouns(phrase=c[:100])
# kkma.nouns(c[:100])
# komoran.nouns(c[:100])
# openkoreantext.nouns(c[:100])

hanna.morphs(ex_text)
hanna.nouns(ex_text)
kkma.nouns(ex_text)
openkoreantext.morphs(ex_text)
openkoreantext.pos(ex_text)

[('아이폰', 'N'),
 ('기다리', 'P'),
 ('다', 'E'),
 ('지치', 'P'),
 ('어', 'E'),
 ('애플공홈', 'N'),
 ('에서', 'J'),
 ('언락폰질러버렸다', 'N'),
 ('6+', 'N'),
 ('128기가실벜', 'N')]

['아이폰', '애플공홈', '언락폰질러버렸다', '6+', '128기가실벜']

['아이',
 '아이폰',
 '폰',
 '애플',
 '애플공홈',
 '공',
 '홈',
 '언락',
 '언락폰',
 '6',
 '128',
 '128기가실버ㅋ',
 '기가',
 '실버',
 'ㅋ']

['아이폰',
 '기다리다',
 '지쳐',
 '애플',
 '공홈',
 '에서',
 '언',
 '락폰',
 '질러',
 '버렸다',
 '6',
 '+',
 '128',
 '기',
 '가',
 '실버',
 'ㅋ']

[('아이폰', 'Noun'),
 ('기다리다', 'Verb'),
 ('지쳐', 'Verb'),
 ('애플', 'Noun'),
 ('공홈', 'Noun'),
 ('에서', 'Josa'),
 ('언', 'Modifier'),
 ('락폰', 'Noun'),
 ('질러', 'Verb'),
 ('버렸다', 'Verb'),
 ('6', 'Number'),
 ('+', 'Punctuation'),
 ('128', 'Number'),
 ('기', 'Noun'),
 ('가', 'Josa'),
 ('실버', 'Noun'),
 ('ㅋ', 'KoreanParticle')]

# ■ DB에서 댓글정보 가져오기

In [237]:
import sqlalchemy ,pickle
# from sqlalchemy import Column, Integer, String, DateTime
from sqlalchemy import *
from sqlalchemy.orm import sessionmaker
from sqlalchemy.ext.declarative import declarative_base

# import MySQLdb
from sqlalchemy import create_engine

In [29]:
import getpass
myid = getpass.getpass("input DB id : ")
mypw = getpass.getpass("input DB pw : ")
# 유니코드? 특수문자들도 갈 수 있도록 utf8mb4로 설정
SQLALCHEMY_DATABASE_URI = 'mysql://'+myid+':'+mypw+'@rds-mysql.cmbehnf2vcrh.ap-northeast-2.rds.amazonaws.com/Webtoon?charset=utf8mb4'

input DB id : ········
input DB pw : ········

In [238]:
engine = create_engine(SQLALCHEMY_DATABASE_URI,convert_unicode=True)#encoding='utf-8')
connectDB = engine.connect()

In [98]:
df_info = pd.read_sql_table('info_duple',connectDB) 
df_chapter = pd.read_sql_table('chapters_final',connectDB)

#### DB쿼리로 가져오기 연습

In [ ]:
#이건 테이블 전체를 가져오는건데... 이건 아무래도 아니지??
# raw_df = pd.read_sql_table('table_name',connectDB)

# 그래서 쿼리를 써서 가져올것이다. 아래는 예제이고~
# query = "SELECT * FROM comments_duple WHERE Region = ? and FeatureName = ? and NewUser =?"
# region = 'US'
# feature = 'tall'
# newUser = 'john'
# raw_df = pd.read_sql_query(query, connectDB, params=(region, feature , newUser))


#이게 진퉁 like % 써서 특정 단어가 들어간 데이터를 찾으려면 파이썬에서는 %%로 써야 %로 인식된다는점 참고~!
# query = "SELECT * FROM comments_duple WHERE daumName like '%%꽃%%' limit "
# username =

In [ ]:
query = "SELECT * FROM comments_duple WHERE articleId = 50137"# limit " #50137회차의 모든 댓글 불러오기
# limits = 5000
raw_df = pd.read_sql_query(query, connectDB)#, params=[username,limits])
raw_df.tail()

#### 텍스트 토크나이징

In [ ]:
# 텍스트 토크나이징 테스트
posls = []
for i,row in raw_df.iterrows():
    print(i,"------------------ 글자길이 :",len(row['content']))
    print(row['content'])
    for text in openkoreantext.pos(row['content']):
        posls.append(text)

In [94]:
# 토큰갯수 조건걸어서 세기
a = pd.DataFrame(posls,columns=["name","pos"])
a['count'] = 1
a.tail(5)
temp = a.groupby(["name","pos"],as_index=False).agg(np.sum).sort_values("count",ascending=False).reset_index(drop=True)
temp[(temp['pos']!='Josa')&(temp['pos']!='Punctuation')&(temp['pos']!='KoreanParticle')]

       name          pos  count
11080   !!!  Punctuation      1
11081    작가         Noun      1
11082     님       Suffix      1
11083  감사해요         Verb      1
11084   !!!  Punctuation      1

       name          pos  count
0         피  Exclamation    344
1        인형         Noun    215
2         님       Suffix    200
3        작가         Noun    194
4        \n      Foreign    147
17       브리         Noun     70
18       너무       Adverb     67
19       7월       Number     64
21        3       Number     63
22       후기         Noun     61
24        꼭         Noun     52
28        ♡      Foreign     42
29        때         Noun     39
30        저         Noun     39
34       웹툰         Noun     36
36     기다리고         Verb     35
37       주행         Noun     34
38        제         Noun     34
39        정         Noun     34
40       헬로         Noun     34
45      무조건         Noun     31
49      단행본         Noun     29
50        잘         Verb     29
52       댓글         Noun     28
53    기다릴게요         Verb     28
55       정말         Noun     27
56       사랑         Noun     27
57       진짜         Noun     27
59       펀딩         Noun     26
60       다시         Noun     25
...     ...          ...    ...
3071    베스트         Noun      1
3072      별         Noun      1
3073     별로         Noun      1
3074     보게         Verb      1
3075   번했는데    Adjective      1
3076    보게되         Verb      1
3077     보겟         Verb      1
3078   보겠구나         Verb      1
3079   보겠네요         Verb      1
3080  보겠습니다         Verb      1
3081      ✨      Foreign      1
3082   번했어요    Adjective      1
3083   번하면서    Adjective      1
3084    발키리         Noun      1
3085     배려         Noun      1
3086     밝게         Verb      1
3087    밝혀요         Verb      1
3088      밤         Noun      1
3089     방금         Noun      1
3090      배         Noun      1
3091     배경         Noun      1
3092     뱃속         Noun      1
3093     번만         Noun      1
3094  버렸습니다         Verb      1
3095  버릴거에요         Verb      1
3096     버세         Noun      1
3097     버텨         Verb      1
3098   버틸게요         Verb      1
3099      ❣      Foreign      1
3100      븅         Noun      1

[2776 rows x 3 columns]

In [ ]:
df_info
df_chapter

# ■ 회차별 댓글 자동 토크나이징 ==> 회차별, 웹툰별 자료 생성==>DB전송
- 댓글마다 추천/비추천, 베댓 시스템이 존재한다
    - 따라서 댓글마다 토크나이징을 할때 해당 댓글의 추천 비추천 배댓을 수치화한 알고리즘을 적용하여 회차별 토큰마다 가중치를 준다.
- **DB화 조건**
    - 회차별DB에 전손될 토큰은 그 수가 해당웹툰회차 댓글수의 0.5%보다 많이 있어야 한다.
    - 전체웹툰DB에 전송될 토큰은 그 수가 전체 웹툰 댓글수의 0.1%보다 많이 있어야 한다.

In [177]:
# 웹툰 아이디 리스트 호출 및 생성
wbt_idls = df_info["id"].values
# wbt_idls

766

In [244]:
# 총 토크나이즈드 댓글 모음
idx = 631
error = []

In [246]:
# 리팩토링 및 각 웹툰의 전체 회차댓글들 토크나이징 
# 총 웹툰의 수 766
import time
# 텍스트 토크나이징 # 현재 진행된 회차 ~ 25
for wbt_id in wbt_idls[631:766]:
    clear_output()
    comment_cnt = 0 # 코멘트 갯수
    wbt_total_txt= pd.DataFrame(columns=["wbt_id","chapter_id","name","pos","count","subcnt","chap_comt_prob"]) #회차별 댓글
    
    print("현재 index",idx,"웹툰이름 :",df_info[df_info['id']==wbt_id]['title'].values[0])
    
    #챕터별 댓글정보 가져오기
    for i,chapt_row in df_chapter[df_chapter['wbt_id']==wbt_id].iterrows():
        
        print("웹툰id:",chapt_row["wbt_id"],"//챕터:",chapt_row["title"]," 전체회차중",i,"번째 진행중 ", end="")
        posls = [] #토큰리스트 저장용 
        recommend = [] #토큰이 있었던 댓글의 추천수 저장용
        dislike = [] #토큰이 있었던 댓글의 반대수 저장용
        best = [] #토큰이 있었던 댓글의 베스트댓글여부 저장용
        query = "SELECT * FROM comments_duple WHERE articleId = "+str(chapt_row['id'])
        print("connecting server...",end="")
        try:
            raw_df = pd.read_sql_query(query, connectDB)
        except:
            print("connection fail... try reconnecting...",end="")
            connectDB = engine.connect()
            raw_df = pd.read_sql_query(query, connectDB)
        print(" success!! now tokenizing...")
        for j,row in raw_df.iterrows():
            if j % 25 == 0:
                print(j,"번째 댓글 --- 글자길이 :",len(row['content']),end="\r")## 이거 한줄만 바꾸기 위해 마지막에 커서를 처음으로 옮겨주는 end방식
#                 print("내용 :",row['content'][:15], end="\r")
            for text in openkoreantext.pos(row['content']):
                posls.append(text)
                recommend.append(row['recommendCount'])
                dislike.append(row['disagreeCount'])
                best.append(row['isBest'])
        comment_cnt += j # 해당 회차의 총 댓글수 세기
        
        a = pd.DataFrame(posls,columns=["name","pos"])
        b = pd.DataFrame(columns=["recommend","dislike","best"]) # 알고리즘 계산용 DF
        a["wbt_id"] = wbt_id
        a["chapter_id"] = chapt_row["id"]
        a["subcnt"] = j
        a['count'] = 1
        
        #추천/비추천/베스트댓글 영향도 계산 알고리즘 적용칼럼 생성-----------
        b["recommend"] = recommend
        b["dislike"] = dislike
        b["best"] = best
        a['algo_count'] = (b['recommend']-b['dislike'])*(b["best"]+1)
        
        
        temp = a.groupby(["wbt_id","chapter_id","name","pos","subcnt"],as_index=False).agg(np.sum).sort_values("count",ascending=False).reset_index(drop=True)
        if j != 0:
            temp["chap_comt_prob"] = temp['count']/j
        else:
            temp["chap_comt_prob"] = 0
        wbt_total_txt = wbt_total_txt.append(temp, ignore_index=True)

    #댓글정보 DB로 전송
    wbt_total_txt.head()
    
    print("Sending Data to RDS server...",end="")
# 회차별 댓글 토큰정보 전송
# notice! : 여기서 회차별 텍스트토큰은 회차별 총 댓글수 대비해서 0.5%이상이 충족되어야만 db데이터로 전송됨
    final_db_send = wbt_total_txt[wbt_total_txt['chap_comt_prob']>=0.005].copy()                                         
    final_db_send.to_sql("txt_token_by_chapter", engine, if_exists="append")
    
# 웹툰별 댓글 토큰정보 전송
# notice! : 여기서 웹툰별 텍스트토큰은 웹툰별 총 댓글수 대비해서 0.1%이상이 충족되어야만 db데이터로 전송됨
    temp = wbt_total_txt[["wbt_id","name","pos","count","algo_count"]].copy()
    temp['count'] = temp['count'].astype(int)
    final_wbtDB_send = temp.groupby(["wbt_id","name","pos"],as_index=False).agg(np.sum).sort_values("count",ascending=False).reset_index(drop=True)
#     final_wbtDB_send.head()
    final_wbtDB_send['wbt_comt_prob'] = final_wbtDB_send['count']/comment_cnt
    final_wbtDB_send['comment_cnt'] = comment_cnt
    final_wbtDB_send = final_wbtDB_send[final_wbtDB_send['wbt_comt_prob']>=0.001]                                         
    final_wbtDB_send.to_sql("txt_token_by_webtoon", engine, if_exists="append")
    
    print("success!")
    idx += 1
    time.sleep(2)
print("Works all done!!")

현재 index 765 웹툰이름 : 여기 고수 추가요!
웹툰id: 1222 //챕터: 프롤로그  전체회차중 43094 번째 진행중 connecting server... success!! now tokenizing...
웹툰id: 1222 //챕터: 1화  전체회차중 43095 번째 진행중 connecting server... success!! now tokenizing...
웹툰id: 1222 //챕터: 2화  전체회차중 43096 번째 진행중 connecting server... success!! now tokenizing...
웹툰id: 1222 //챕터: 3화  전체회차중 43097 번째 진행중 connecting server... success!! now tokenizing...
웹툰id: 1222 //챕터: 4화  전체회차중 43098 번째 진행중 connecting server... success!! now tokenizing...
웹툰id: 1222 //챕터: 5화  전체회차중 43099 번째 진행중 connecting server... success!! now tokenizing...
웹툰id: 1222 //챕터: 6화  전체회차중 43100 번째 진행중 connecting server... success!! now tokenizing...
웹툰id: 1222 //챕터: 7화  전체회차중 43101 번째 진행중 connecting server... success!! now tokenizing...
웹툰id: 1222 //챕터: 8화  전체회차중 43102 번째 진행중 connecting server... success!! now tokenizing...
웹툰id: 1222 //챕터: 9화  전체회차중 43103 번째 진행중 connecting server... success!! now tokenizing...
웹툰id: 1222 //챕터: 10화  전체회차중 43104 번째 진행중 connecting server... success!! now tokenizing...
웹툰id: 1222 //챕터: 11화  전체회차중 43105 번째 진행중 connecting server... success!! now tokenizing...
웹툰id: 1222 //챕터: 휴재공지  전체회차중 43106 번째 진행중 connecting server... success!! now tokenizing...
웹툰id: 1222 //챕터: 12화  전체회차중 43107 번째 진행중 connecting server... success!! now tokenizing...
웹툰id: 1222 //챕터: 13화  전체회차중 43108 번째 진행중 connecting server... success!! now tokenizing...
웹툰id: 1222 //챕터: 14화  전체회차중 43109 번째 진행중 connecting server... success!! now tokenizing...
웹툰id: 1222 //챕터: 15화  전체회차중 43110 번째 진행중 connecting server... success!! now tokenizing...
웹툰id: 1222 //챕터: 16화  전체회차중 43111 번째 진행중 connecting server... success!! now tokenizing...
웹툰id: 1222 //챕터: 17화  전체회차중 43112 번째 진행중 connecting server... success!! now tokenizing...
웹툰id: 1222 //챕터: 18화  전체회차중 43113 번째 진행중 connecting server... success!! now tokenizing...
웹툰id: 1222 //챕터: 19화  전체회차중 43114 번째 진행중 connecting server... success!! now tokenizing...
웹툰id: 1222 //챕터: 20화  전체회차중 43115 번째 진행중 connecting server... success!! now tokenizing...
웹툰id: 1222 //챕터: 21화  전체회차중 43116 번째 진행중 connecting server... success!! now tokenizing...
웹툰id: 1222 //챕터: 22화  전체회차중 43117 번째 진행중 connecting server... success!! now tokenizing...
웹툰id: 1222 //챕터: 에필로그  전체회차중 43118 번째 진행중 connecting server... success!! now tokenizing...
웹툰id: 1222 //챕터: 후기  전체회차중 43119 번째 진행중 connecting server... success!! now tokenizing...

   algo_count  chap_comt_prob chapter_id count name          pos subcnt wbt_id
0      3415.0        0.241722      31752   219    .  Punctuation    906   1222
1      4658.0        0.211921      31752   192    이         Josa    906   1222
2      3403.0        0.207506      31752   188  ...  Punctuation    906   1222
3      5884.0        0.196468      31752   178   ..  Punctuation    906   1222
4      3223.0        0.182119      31752   165    가         Josa    906   1222

Sending Data to RDS server...success!
Works all done!!

---
# ■ 텍스트 특징추출 및 유사도 추출
- TF-IDF 개념 및 변형활용

- 텍스트 토큰 벡터화 및 유사도 파악
    1. 일부 댓글로 유사댓글 찾아보기
    2. 일부 회차 댓글토큰들로 유사 회차 및 내용 찾아보기 (문제점 댓글의 수가 현저히 다를 수 있다. 평균화 작업 필요)
- 실제 자료 테스트
    1. 회차별 특징 및 유사도 추출
    2. 웹툰별 특징 및 유사도 추출